/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant_s;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;
/**
 *
 * @author Sazid
 */
public class Restaurants extends javax.swing.JFrame {

   double firstnum;
   double secondnum;
   double result;
   String operations;
   double Nigerian_Naira=302.12;
   double US_doller=1.53;
   double Kenyan_Shilling=156.21;
   double Brazilian_Real=5.86;
   double Canadian_doller=2.03;
   double Indian_Rupee=100.68;
   double Philipian_peao=71.74;
//  public String[] checkbox = {"jCchicburger", "jCchicburgermeal", "jCbeconchicburger","jCtax","jChkhomedelivery"};
    
   
   public Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jCchicburger = new javax.swing.JCheckBox();
        jCchicburgermeal = new javax.swing.JCheckBox();
        jCbeconchicburger = new javax.swing.JCheckBox();
        jtxtChicBurger = new javax.swing.JTextField();
        jtxtchicburgermeal = new javax.swing.JTextField();
        jtxtbeconchicburger = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCtax = new javax.swing.JCheckBox();
        jChkhomedelivery = new javax.swing.JCheckBox();
        jCombodrinks = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jcmbCurrency = new javax.swing.JComboBox();
        jtxtconvert = new javax.swing.JTextField();
        jlebelconvert = new javax.swing.JTextField();
        jBclose = new javax.swing.JButton();
        jBconvert = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreareceipt = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jBtnplussub = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jBtnsub = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnplus = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnmult = new javax.swing.JButton();
        jBtndiv = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnequals = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtndot = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jBtnreceipt = new javax.swing.JButton();
        jBtntotal = new javax.swing.JButton();
        jBtnexit = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlebelcostofmeal = new javax.swing.JTextField();
        jlebelcostofdelivery = new javax.swing.JTextField();
        jlebelcostofdrinks = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtsubtotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jLebeltotal = new javax.swing.JLabel();
        jLebelsubtotal = new javax.swing.JLabel();
        jLebeltax = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 800));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jCchicburger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCchicburger.setText("Chicken Burger");
        jCchicburger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCchicburgerMouseClicked(evt);
            }
        });
        jCchicburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCchicburgerActionPerformed(evt);
            }
        });

        jCchicburgermeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCchicburgermeal.setText("Chicken Burger Meal");
        jCchicburgermeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCchicburgermealMouseClicked(evt);
            }
        });

        jCbeconchicburger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCbeconchicburger.setText("Becon & Chicken burger");
        jCbeconchicburger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCbeconchicburgerMouseClicked(evt);
            }
        });
        jCbeconchicburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbeconchicburgerActionPerformed(evt);
            }
        });

        jtxtChicBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChicBurger.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtChicBurger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtchicburgermeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtchicburgermeal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtchicburgermeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtxtbeconchicburger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtbeconchicburger.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtbeconchicburger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Drinks");

        jCtax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCtax.setText("Tax");
        jCtax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCtaxMouseClicked(evt);
            }
        });
        jCtax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtaxActionPerformed(evt);
            }
        });

        jChkhomedelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkhomedelivery.setText("Home Delivery");
        jChkhomedelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkhomedeliveryMouseClicked(evt);
            }
        });
        jChkhomedelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkhomedeliveryActionPerformed(evt);
            }
        });

        jCombodrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCombodrinks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select a drink..", "Coffee", "Ice Coffee", "Tea", "Ice Tea", "Cola", "Coke", " " }));
        jCombodrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCombodrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombodrinksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jCbeconchicburger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtbeconchicburger, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCtax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jChkhomedelivery))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCchicburgermeal)
                            .addComponent(jCchicburger))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtChicBurger)
                            .addComponent(jtxtchicburgermeal, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCombodrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCchicburger)
                    .addComponent(jtxtChicBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCchicburgermeal)
                    .addComponent(jtxtchicburgermeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbeconchicburger)
                    .addComponent(jtxtbeconchicburger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jCombodrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCtax)
                    .addComponent(jChkhomedelivery))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jcmbCurrency.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcmbCurrency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose one ...", "Nigeria", "US", "Kenyan", "Brazilian", "Canada", "India", "Philipian", " ", " " }));

        jtxtconvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtconvert.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtconvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlebelconvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlebelconvert.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jlebelconvert.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.white));

        jBclose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBclose.setText("Close");
        jBclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBcloseMouseClicked(evt);
            }
        });
        jBclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcloseActionPerformed(evt);
            }
        });

        jBconvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBconvert.setText("Convert");
        jBconvert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBconvertMouseClicked(evt);
            }
        });
        jBconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcmbCurrency, 0, 388, Short.MAX_VALUE)
                            .addComponent(jtxtconvert)
                            .addComponent(jlebelconvert)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jBconvert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBclose, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlebelconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBconvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBclose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextAreareceipt.setColumns(20);
        jTextAreareceipt.setRows(5);
        jScrollPane1.setViewportView(jTextAreareceipt);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Recept", jPanel9);

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("C");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jBtnplussub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnplussub.setText("+/-");
        jBtnplussub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnplussubActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("#");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jBtnsub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnsub.setText("-");
        jBtnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnsubActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtnplus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnplus.setText("+");
        jBtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnplusActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtnmult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnmult.setText("*");
        jBtnmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnmultActionPerformed(evt);
            }
        });

        jBtndiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtndiv.setText("/");
        jBtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtndivActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtnequals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnequals.setText("=");
        jBtnequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnequalsActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtndot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtndot.setText(".");
        jBtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtndotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtDisplay)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jBtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnequals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jBtnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jBtnmult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnplussub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)))))
                .addGap(70, 70, 70))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnplussub, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jBtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jBtnsub, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jBtnmult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jBtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnequals, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculator", jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jBtnreceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnreceipt.setText("Receipt");
        jBtnreceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnreceiptMouseClicked(evt);
            }
        });
        jBtnreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnreceiptActionPerformed(evt);
            }
        });

        jBtntotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtntotal.setText("TOTAL");
        jBtntotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtntotalMouseClicked(evt);
            }
        });
        jBtntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtntotalActionPerformed(evt);
            }
        });

        jBtnexit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnexit.setText("Exit");
        jBtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnexitActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Reset");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jBtntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jBtnreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jBtnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnreceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtntotal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cost Of Meal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cost Of delivery");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Cost Of Drinks");

        jlebelcostofmeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlebelcostofmeal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jlebelcostofmeal.setText("0.00");
        jlebelcostofmeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlebelcostofmealActionPerformed(evt);
            }
        });

        jlebelcostofdelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlebelcostofdelivery.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jlebelcostofdrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlebelcostofdrinks.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlebelcostofmeal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlebelcostofdelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlebelcostofdrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlebelcostofdrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlebelcostofmeal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlebelcostofdelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtxtsubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtsubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtTax.setText("0.00");

        jLebeltotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLebeltotal.setText("Total :");

        jLebelsubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLebelsubtotal.setText("Sub Total:");

        jLebeltax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLebeltax.setText("TAX :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLebeltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLebelsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLebeltax, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtsubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLebelsubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLebeltax, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLebeltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Restuarant management systems");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
       String Enternumber= jtxtDisplay.getText() +jBtn7.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
         String Enternumber= jtxtDisplay.getText() +jBtn8.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        String Enternumber= jtxtDisplay.getText() +jBtn9.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
       String Enternumber= jtxtDisplay.getText() +jBtn4.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
      String Enternumber= jtxtDisplay.getText() +jBtn5.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
      String Enternumber= jtxtDisplay.getText() +jBtn6.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        String Enternumber= jtxtDisplay.getText() +jBtn1.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        String Enternumber= jtxtDisplay.getText() +jBtn2.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        String Enternumber= jtxtDisplay.getText() +jBtn3.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        String Enternumber= jtxtDisplay.getText() +jBtn0.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtndotActionPerformed
        String Enternumber= jtxtDisplay.getText() +jBtndot.getText();
       jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtndotActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jtxtDisplay.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String backspace=null;
        
        if(jtxtDisplay.getText().length()>0){
        StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
        strB.deleteCharAt(jtxtDisplay.getText().length() -1);
        backspace=strB.toString();
        jtxtDisplay.setText(backspace);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnplusActionPerformed
        firstnum=Double.parseDouble(jtxtDisplay.getText());
      jtxtDisplay.setText("");
      operations="+";
    }//GEN-LAST:event_jBtnplusActionPerformed

    private void jBtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtndivActionPerformed
      firstnum=Double.parseDouble(jtxtDisplay.getText());
      jtxtDisplay.setText("");
      operations="/";
    }//GEN-LAST:event_jBtndivActionPerformed

    private void jBtnmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnmultActionPerformed
        firstnum=Double.parseDouble(jtxtDisplay.getText());
      jtxtDisplay.setText("");
      operations="*";
    }//GEN-LAST:event_jBtnmultActionPerformed

    private void jBtnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnsubActionPerformed
        firstnum=Double.parseDouble(jtxtDisplay.getText());
      jtxtDisplay.setText("");
      operations="-";
    }//GEN-LAST:event_jBtnsubActionPerformed

    private void jBtnplussubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnplussubActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops=ops*(-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnplussubActionPerformed

    private void jBtnequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnequalsActionPerformed
       String answer;
       secondnum=Double.parseDouble(jtxtDisplay.getText());
       if (operations=="+")
       {
       result=firstnum+secondnum;
       answer=String.format("%.2f",result);
       jtxtDisplay.setText(answer);
       }
       else if (operations=="-")
       {
       result=firstnum-secondnum;
       answer=String.format("%.2f",result);
       jtxtDisplay.setText(answer);
       }
       else if (operations=="*")
       {
       result=firstnum*secondnum;
       answer=String.format("%.2f",result);
       jtxtDisplay.setText(answer);
       }
       else if (operations=="/")
       {
       result=firstnum/secondnum;
       answer=String.format("%.2f",result);
       jtxtDisplay.setText(answer);
       }
    }//GEN-LAST:event_jBtnequalsActionPerformed

    private void jCombodrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombodrinksActionPerformed
       
        double Tea=1.20;
        double Ice_Tea=0.90;
        double Coffee=2.50;
        double Ice_Coffee=1.10;
        double Cola=2.10;
        double Coke=1.60;
        
        if(jCombodrinks.getSelectedItem().equals("Tea"))
        {
        String cTea=String.format("%.2f", Tea);
        jlebelcostofdrinks.setText(cTea);
        }
        
        if(jCombodrinks.getSelectedItem().equals("Ice Tea"))
        {
        String cIce_Tea=String.format("%.2f", Ice_Tea);
        jlebelcostofdrinks.setText(cIce_Tea);
        }
        if(jCombodrinks.getSelectedItem().equals("Coffee"))
        {
        String cCoffee=String.format("%.2f", Coffee);
        jlebelcostofdrinks.setText(cCoffee);
        }
        if(jCombodrinks.getSelectedItem().equals("Ice Coffee"))
        {
        String cIce_Coffee=String.format("%.2f", Ice_Coffee);
        jlebelcostofdrinks.setText(cIce_Coffee);
        }
        if(jCombodrinks.getSelectedItem().equals("Cola"))
        {
        String cCola=String.format("%.2f", Cola);
        jlebelcostofdrinks.setText(cCola);
        }
         if(jCombodrinks.getSelectedItem().equals("Coke"))
        {
        String cCoke=String.format("%.2f", Coke);
        jlebelcostofdrinks.setText(cCoke);
        }
        
        
        
    }//GEN-LAST:event_jCombodrinksActionPerformed

    private void jBtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnexitActionPerformed

    private void jChkhomedeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkhomedeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkhomedeliveryActionPerformed

    private void jChkhomedeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkhomedeliveryMouseClicked
        double iDelivery=3.39;
        
        if (jChkhomedelivery.isSelected())
        {
        String PDelivery =String.format("%.2f", iDelivery);
        jlebelcostofdelivery.setText(PDelivery);
        
        }
        else {
        jlebelcostofdelivery.setText(null);
        }
               
    }//GEN-LAST:event_jChkhomedeliveryMouseClicked

    private void jBtnreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnreceiptActionPerformed
       
        double qty1=Double.parseDouble(jtxtChicBurger.getText());
        double qty2=Double.parseDouble(jtxtchicburgermeal.getText());
        double qty3=Double.parseDouble(jtxtbeconchicburger.getText());
        
        jTextAreareceipt.append("\t Restaurent Management System: \n\n" + 
                "\nChicken Burger:\t\t"+qty1+" unit" +
                "\nChicken Burger Meal:\t\t "+qty2+" unit"+ 
                "\nBecon and Chicken Burger:\t\t"+qty3+" unit"+
                "\nthank you for purchese");
    }//GEN-LAST:event_jBtnreceiptActionPerformed

    private void jBtnreceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnreceiptMouseClicked
       
       
        
    }//GEN-LAST:event_jBtnreceiptMouseClicked

    private void jCchicburgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCchicburgerMouseClicked
            double cMeal=Double.parseDouble(jlebelcostofmeal.getText());
              double ChicBurger;
       ChicBurger = Double.parseDouble(jtxtChicBurger.getText());
              double iChicBurger=2.39;
              
              if(jCchicburger.isSelected())
              {
                  double done;
                  done=(ChicBurger * iChicBurger) + cMeal;
                  String pMeal=String.format("%.2f", done);
                  jlebelcostofmeal.setText(pMeal);
             
              }
              else {
                  double done;
                  done=cMeal-(ChicBurger * iChicBurger);
                  String pMeal=String.format("%.2f", done);
                  jlebelcostofmeal.setText(pMeal);
              }
            
    }//GEN-LAST:event_jCchicburgerMouseClicked

    private void jCchicburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCchicburgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCchicburgerActionPerformed

    private void jCchicburgermealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCchicburgermealMouseClicked
        double cMeal=Double.parseDouble(jlebelcostofmeal.getText());
              double ChicBurgerMeal;
       ChicBurgerMeal = Double.parseDouble(jtxtchicburgermeal.getText());
              double iChicBurgerMeal=4.00;
              
              if(jCchicburgermeal.isSelected())
              {
                  double done;
                  done=(ChicBurgerMeal * iChicBurgerMeal) + cMeal;
                  String pMeal=String.format("%.2f", done);
                  jlebelcostofmeal.setText(pMeal);
             
              }
              else {
                  double done;
                  done=cMeal-(ChicBurgerMeal * iChicBurgerMeal);
                  String pMeal=String.format("%.2f", done);
                  jlebelcostofmeal.setText(pMeal);
              }
    }//GEN-LAST:event_jCchicburgermealMouseClicked

    private void jlebelcostofmealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlebelcostofmealActionPerformed
   
    }//GEN-LAST:event_jlebelcostofmealActionPerformed

    private void jCbeconchicburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbeconchicburgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbeconchicburgerActionPerformed

    private void jCbeconchicburgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCbeconchicburgerMouseClicked
        double cMeal=Double.parseDouble(jlebelcostofmeal.getText());
              double BeconChicBurger;
       BeconChicBurger = Double.parseDouble(jtxtbeconchicburger.getText());
              double iBeconChicBurger=4.00;
              
              if(jCbeconchicburger.isSelected())
              {
                  double done;
                  done=(BeconChicBurger * iBeconChicBurger) + cMeal;
                  String pMeal=String.format("%.2f", done);
                  jlebelcostofmeal.setText(pMeal);
             
              }
              else {
                  double done;
                  done=cMeal-(BeconChicBurger * iBeconChicBurger);
                  String pMeal=String.format("%.2f", done);
                  jlebelcostofmeal.setText(pMeal);
              }
    }//GEN-LAST:event_jCbeconchicburgerMouseClicked

    private void jBtntotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtntotalMouseClicked
        double total1=Double.parseDouble(jlebelcostofdelivery.getText());
        double total2=Double.parseDouble(jlebelcostofdrinks.getText());
        double total3=Double.parseDouble(jlebelcostofmeal.getText());
        double total4=Double.parseDouble(jtxtTax.getText());
        
        double subtotal=(total1+total2+total3);
        String isubtotal=String.format("%.2f", subtotal);
        jtxtsubtotal.setText(isubtotal);
        double alltotal=(total1+total2+total3+total4);
        String ialltotal=String.format("%.2f", alltotal);
        jtxtTotal.setText(ialltotal);
        
    }//GEN-LAST:event_jBtntotalMouseClicked

    private void jBtntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtntotalActionPerformed
//        double total1=Double.parseDouble(jlebelcostofdelivery.getText());
//        double total2=Double.parseDouble(jlebelcostofdrinks.getText());
//        double total3=Double.parseDouble(jlebelcostofmeal.getText());
//       
//        
//        double subtotal=(total1+total2+total3)/100;
//        String isubtotal=String.format("%.2f", subtotal);
//        jtxtTax.setText(isubtotal);
    }//GEN-LAST:event_jBtntotalActionPerformed

    private void jCtaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCtaxMouseClicked
        double total1=Double.parseDouble(jlebelcostofdelivery.getText());
        double total2=Double.parseDouble(jlebelcostofdrinks.getText());
        double total3=Double.parseDouble(jlebelcostofmeal.getText());
       
        if (jCtax.isSelected()){
        double subtotal=(total1+total2+total3)/100;
        String isubtotal=String.format("%.2f", subtotal);
        jtxtTax.setText(isubtotal);}
        else{
        jtxtTax.setText("0.00");
        }
    }//GEN-LAST:event_jCtaxMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        jlebelcostofdelivery.setText(null);
        jlebelcostofdrinks.setText(null);
        jlebelcostofmeal.setText("0.00");
        jtxtTotal.setText(null);
        jtxtsubtotal.setText(null);
        jtxtTax.setText("0.00");
        jtxtChicBurger.setText(null);
        jtxtchicburgermeal.setText(null);
        jtxtbeconchicburger.setText(null);
        jTextAreareceipt.setText(null);
        jCombodrinks.setSelectedIndex(0);
        
       
               
              if(jCbeconchicburger.isSelected()){
              jCbeconchicburger.setSelected(false);
              }
              
              if(jCchicburger.isSelected()){
              jCchicburger.setSelected(false);
              }
              
              if(jCchicburgermeal.isSelected()){
              jCchicburgermeal.setSelected(false);
              }
              
              if(jCtax.isSelected()){
              jCtax.setSelected(false);
              }
              if(jChkhomedelivery.isSelected())
              {
              jChkhomedelivery.setSelected(false);
              }
       
       
    }//GEN-LAST:event_jButton8MouseClicked

    private void jCtaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCtaxActionPerformed

    private void jBcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBcloseActionPerformed

    private void jBconvertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBconvertMouseClicked
        double british_pound=Double.parseDouble(jtxtconvert.getText());
        
        if(jcmbCurrency.getSelectedItem().equals("Nigeria"))
        {
            String cConvert1=String.format("N %.2f", british_pound*Nigerian_Naira);
            jlebelconvert.setText(cConvert1);
        }
        if(jcmbCurrency.getSelectedItem().equals("US"))
        {
            String cConvert1=String.format("$ %.2f", british_pound*US_doller);
            jlebelconvert.setText(cConvert1);
        }
        if(jcmbCurrency.getSelectedItem().equals("Kenyan"))
        {
            String cConvert1=String.format("K %.2f", british_pound*Kenyan_Shilling);
            jlebelconvert.setText(cConvert1);
        }
        if(jcmbCurrency.getSelectedItem().equals("Brazilian"))
        {
            String cConvert1=String.format("B %.2f", british_pound*Brazilian_Real);
            jlebelconvert.setText(cConvert1);
        }
        if(jcmbCurrency.getSelectedItem().equals("Canada"))
        {
            String cConvert1=String.format("C %.2f", british_pound*Canadian_doller);
            jlebelconvert.setText(cConvert1);
        }
        if(jcmbCurrency.getSelectedItem().equals("India"))
        {
            String cConvert1=String.format("I %.2f", british_pound*Indian_Rupee);
            jlebelconvert.setText(cConvert1);
        }
        if(jcmbCurrency.getSelectedItem().equals("Philipian"))
        {
            String cConvert1=String.format("P %.2f", british_pound*Philipian_peao);
            jlebelconvert.setText(cConvert1);
        }
    }//GEN-LAST:event_jBconvertMouseClicked

    private void jBcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcloseMouseClicked
        jtxtconvert.setText(null);
        jlebelconvert.setText(null);
        jcmbCurrency.setSelectedIndex(0);
    }//GEN-LAST:event_jBcloseMouseClicked

    private void jBconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBconvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBclose;
    private javax.swing.JButton jBconvert;
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtndiv;
    private javax.swing.JButton jBtndot;
    private javax.swing.JButton jBtnequals;
    private javax.swing.JButton jBtnexit;
    private javax.swing.JButton jBtnmult;
    private javax.swing.JButton jBtnplus;
    private javax.swing.JButton jBtnplussub;
    private javax.swing.JButton jBtnreceipt;
    private javax.swing.JButton jBtnsub;
    private javax.swing.JButton jBtntotal;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCbeconchicburger;
    private javax.swing.JCheckBox jCchicburger;
    private javax.swing.JCheckBox jCchicburgermeal;
    private javax.swing.JCheckBox jChkhomedelivery;
    private javax.swing.JComboBox jCombodrinks;
    private javax.swing.JCheckBox jCtax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLebelsubtotal;
    private javax.swing.JLabel jLebeltax;
    private javax.swing.JLabel jLebeltotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreareceipt;
    private javax.swing.JComboBox jcmbCurrency;
    private javax.swing.JTextField jlebelconvert;
    private javax.swing.JTextField jlebelcostofdelivery;
    private javax.swing.JTextField jlebelcostofdrinks;
    private javax.swing.JTextField jlebelcostofmeal;
    private javax.swing.JTextField jtxtChicBurger;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtbeconchicburger;
    private javax.swing.JTextField jtxtchicburgermeal;
    private javax.swing.JTextField jtxtconvert;
    private javax.swing.JTextField jtxtsubtotal;
    // End of variables declaration//GEN-END:variables
}
